### ISSUE TITLE
Income tax calculator has an error.

### ISSUE THREAD

**Issue by aanjalii2** [AnushaaPandey/Tax-Calculator-System#10]

**Comment by AnushaaPandey** [comment]
Will look at it can you specify what was the error

**Comment by aanjalii2** [comment]
![image](https://user-images.githubusercontent.com/109156000/235286751-a0f68b52-b942-4c5b-abfd-4ae861ae526a.png)
here is the error

**Comment by AnushaaPandey** [comment]
I will let you know when that error is handled.
