### ISSUE TITLE
 In the frontend make sure to put the log out feature in the pop up in user icon

### ISSUE THREAD

**Issue by AnushaaPandey** [AnushaaPandey/Tax-Calculator-System#3]
As per the client request it is easier to log out from the system if the logout feature is in the user icon more than it being inside the settings.

**Comment by SambridhikaShrestha** [comment]
I will do it in the beginning of the sprint2

**Comment by AnushaaPandey** [comment]
Is there any chances that you can do it before Sprint 1?

**Comment by Nikita2228054** [comment]
completed
