### ISSUE TITLE
Merge Conflict Issues

### ISSUE THREAD

**Issue by AnushaaPandey** [AnushaaPandey/Tax-Calculator-System#5]
Developers please make sure that the only latest code of sign up and login is kept in your branches. Since the previous and the latest code is being conflicted in both of your codes. Discuss and please make sure to keep the latest code.

<img width="960" alt="Issue Tracking 2" src="https://user-images.githubusercontent.com/127808296/228109954-2dce359f-54e5-4e0b-a0b1-d2978559b1f6.png">

**Comment by SambridhikaShrestha** [comment]
After Nikita upload the final code you can combine them

**Comment by Nikita2228054** [comment]
The latest files are uploaded

**Comment by Nikita2228054** [comment]
[new.zip](https://github.com/AnushaaPandey/Tax-Calculator-System/files/11131358/new.zip)
